version: '2'

services: 
    ftpd_server:
        image: stilliard/pure-ftpd:hardened
        container_name: pure-ftpd
        ports: 
            - 21:21
            - 30000-30009:30000-30009
        volumes: 
            - "./data:/home"
            - "./passwd:/etc/pure-frpd/passwd"
        environment: 
            PUBLICHOST: "localhost"
            FTP_USER_NAME: username
            FTP_USER_PASS: mypass
            FTP_USER_HOME: /home/username